sudo: required
addons:
  addons: 
  chrome: beta
  apt:
    packages:
    - chromium-chromedriver
language: node_js
node_js:
- 10
cache:
  directories:
  - node_modules
before_script:
- export DISPLAY=:99.0
- export PATH=$PATH:/usr/lib/chromium-browser/
- "./node_modules/ionic/bin/ionic serve --no-open &"
- sleep 30
install:
- npm i
- npm install -g cordova ionic
- npm run e2e-update
script:
# - npm run e2e
- npm run test
- ionic cordova build browser --release --prod
notifications:
  pushover:
    api_key:
      secure: FpOyalFnM1J5wCO+3eWmhrO4OCMLwscYV9eEfh1LZUVZBrQPi1Jy6rW1f5O3Xa+tB6dVJM45sGDXTnh50QMIxfP/k/9Hyy3LtGct8YR7r/BtQpZ9MpfhIsXF0rhbMrNw1CGk4n3uNyqI0zwuvQfzVwqtV7cQiqPxUsOJ0v24gm0+o2jAg+AgSOzhzA78+/tJgM4g+bzq/u7lcu/kN+Ij1X2WUmRVkNkSsHg2b1dHAPV0FCWK+eTEJ/y9/19Hh8mv7oxXdp9rrlHCphTADm1jDVy6Xk4c/og5bxm++mLZsA7JlPyda70jsKGPuaHTQR5hPR7ma1WP8pkJ35iQRbUsxeDTHMUpMUfeZWFPmnX7Va9y5aI0AlS4AUJeHBzkEy53MorvK+A6xLPz+2IcOf8U3cBYtjdFFAAEUDzOuX4uMPzHlIVRzsiBk+miaqm7kEsAOj5TPh5P9NezqpMCforYgfupXUgj9A2r2Lq3GhU3x4ZlrGbaSe5aIYynUiWZoosZbuRHVhIeUZR8iV4AseAGXV0fkng4k+YV1RxmHkAe1UfmUw7R2IREf4BZlxCcKUKXqz7vdOHmE5PhVoPzCb92M/9Tgxvb4uUE0B6RLGpMwIKgivSSL1jn2PYDzk6FqLPcAJArKAZytIFem34S2jmzT3x0jpa8HspM27kr4lLGpww=
    users:
      secure: se2uFseEvvMwpbWRHx2A5A3ekeP3uJ25KEAL57Io/wZgCVKuk8XXinyNTAbGxib0ipvED7S80YFmO7S0yaBaLJDcSJtEdnGcDn8gBnFmftU2il2ovGpfxv/Xp50CSYcqizGs16x+2LcdtZBG1hdICf2wEJQXvhObD7B6XjVgkKinICgr1ZZeUxNBBU1hyfsP5V/goAsqrIC7TFicmcSgJYWl6N906ZYZ20YOkziHqfpt6FeLwk2C4YpxEFYIaDJLtgqTttXQ8owph77FnvuA21Mo8W/e8MvyLJ5Hq10KH3h5vAuIFnCM/xkhvDoHSVA5V96g4567K7xy37Aa4OsyMV/dhTDku0Ik65cWWvgSflc1arDYsiiQKOku5IXYqy0rTU/0ouMuINqdUidSjwLy5765QTIUhrff1vSAdcpiyfLPceoQapzudcEgnwGF9BqzHTHv5c570MwyJn/BzZpy2iGqm6RfVmbyBeweR1rx/0OxQkeHvncgMZY7uZLtI0A6eSlJq5m1VyrRYlel4bc4erWI0swulvXDWzkuUGhQxTVhYx5G+G2xnbAXeS0Eb/jWCXQiQrp64JKGYvNiQM0+ayel60Y5wmWFYdH9PLhlZHOfuS8mkzLAo3aQuU9inwZ0YxYhk7XVPKQ5R9bjfeW4gmSIIOYVzuNHK8k8V+0DX0Y=
deploy:
- provider: firebase
  token:
    secure: DM1rjrqsTGP14LtBG++NI1alVOnuZdog4zBntSD/MSDVNr12R7wccFZFZzTqsecCG/xaHRdKpImB96vKcmT+j3Yw/60ARxMwA0monXVyZWo17mQokyKH2vNbBJ3TNG8pUQS97Ei1V5m+L3n1mpx+xJIKJ4wWoLZ8pTPgWAS3lghmeh8wZHsdCz+dW116cR/Tm/SKkSefRwYCwron7o6LWPN83gfI11z/O6h84b2wl096klhSeLc2Ji6DtnBnODQwTQgTjP8FE7kFEw9M8Bipgjxq3Od/8dPyrQviz/pHfZ0srVvtMwAygdoRgToBXngIRJpooKdvk4oDIOxgs6WUOEQVKgPJPvmuKoIyLdjWP5z4kGOEHPulqpHZbrnQ+2sLQOZ0Ab9An1EtIEPMGiFSXBjZTF2cUn5ZuznvFouo0fJ8wLMCwGc1qc6405pm5Psg7XaIIs7H0rLHXsXYFt2GYGyXiWe7djkM2jjtq9SjaCMX0+4Z4aBVKAlQnGwLDHhnS7YUzypChu5SRHwp7pCGZYg0kqdtPx3qfICcOc3/Eyjk44w8owW2XsJbN9j7VQtPI9XvAPFSAbFXAtvzGhgA+FPGmkiI3mC+khV5BpjZttmpWTJDC9B8ID/ac62GcAWuM39Hd3jVsTNpjhsUCANpG84bwUfwRkC+PJ7qUm1+VmU=
  project: myetpwallet-app
  skip_cleanup: true
  on:
    branch: master
- provider: firebase
  token:
    secure: DM1rjrqsTGP14LtBG++NI1alVOnuZdog4zBntSD/MSDVNr12R7wccFZFZzTqsecCG/xaHRdKpImB96vKcmT+j3Yw/60ARxMwA0monXVyZWo17mQokyKH2vNbBJ3TNG8pUQS97Ei1V5m+L3n1mpx+xJIKJ4wWoLZ8pTPgWAS3lghmeh8wZHsdCz+dW116cR/Tm/SKkSefRwYCwron7o6LWPN83gfI11z/O6h84b2wl096klhSeLc2Ji6DtnBnODQwTQgTjP8FE7kFEw9M8Bipgjxq3Od/8dPyrQviz/pHfZ0srVvtMwAygdoRgToBXngIRJpooKdvk4oDIOxgs6WUOEQVKgPJPvmuKoIyLdjWP5z4kGOEHPulqpHZbrnQ+2sLQOZ0Ab9An1EtIEPMGiFSXBjZTF2cUn5ZuznvFouo0fJ8wLMCwGc1qc6405pm5Psg7XaIIs7H0rLHXsXYFt2GYGyXiWe7djkM2jjtq9SjaCMX0+4Z4aBVKAlQnGwLDHhnS7YUzypChu5SRHwp7pCGZYg0kqdtPx3qfICcOc3/Eyjk44w8owW2XsJbN9j7VQtPI9XvAPFSAbFXAtvzGhgA+FPGmkiI3mC+khV5BpjZttmpWTJDC9B8ID/ac62GcAWuM39Hd3jVsTNpjhsUCANpG84bwUfwRkC+PJ7qUm1+VmU=
  project: myetpwallet-testnet
  skip_cleanup: true
  on:
    branch: testnet
- provider: firebase
  token:
    secure: DM1rjrqsTGP14LtBG++NI1alVOnuZdog4zBntSD/MSDVNr12R7wccFZFZzTqsecCG/xaHRdKpImB96vKcmT+j3Yw/60ARxMwA0monXVyZWo17mQokyKH2vNbBJ3TNG8pUQS97Ei1V5m+L3n1mpx+xJIKJ4wWoLZ8pTPgWAS3lghmeh8wZHsdCz+dW116cR/Tm/SKkSefRwYCwron7o6LWPN83gfI11z/O6h84b2wl096klhSeLc2Ji6DtnBnODQwTQgTjP8FE7kFEw9M8Bipgjxq3Od/8dPyrQviz/pHfZ0srVvtMwAygdoRgToBXngIRJpooKdvk4oDIOxgs6WUOEQVKgPJPvmuKoIyLdjWP5z4kGOEHPulqpHZbrnQ+2sLQOZ0Ab9An1EtIEPMGiFSXBjZTF2cUn5ZuznvFouo0fJ8wLMCwGc1qc6405pm5Psg7XaIIs7H0rLHXsXYFt2GYGyXiWe7djkM2jjtq9SjaCMX0+4Z4aBVKAlQnGwLDHhnS7YUzypChu5SRHwp7pCGZYg0kqdtPx3qfICcOc3/Eyjk44w8owW2XsJbN9j7VQtPI9XvAPFSAbFXAtvzGhgA+FPGmkiI3mC+khV5BpjZttmpWTJDC9B8ID/ac62GcAWuM39Hd3jVsTNpjhsUCANpG84bwUfwRkC+PJ7qUm1+VmU=
  project: myetpwallet-dev
  skip_cleanup: true
  on:
    branch: dev
